### ISSUE TITLE
PyPY?

### ISSUE THREAD

**Issue by Marketcentric** [tailhook/zorro#10]
Hi Paul,
Very nice work on Zorro and Zerogw. Question (not an issue) , have you tried this under pypy?  Not a show stopper just curious (with xmq, greenlets, etc. baked in its hard to predict).  Also, what versions of python are supported and/or recommended for zorro apps?

Thanks,
Ross

**Comment by tailhook** [comment]
Hi Ross,

Zorro works on python >= 3.2. The `zorro.web` module in `newweb` branch (which will be merged to master soon) requires python 3.3

Haven't tried it on PyPy because later doesn't support python3, AFAIK (does it already?)

**Comment by Marketcentric** [comment]
Paul,
Thanks.  Some pretty exciting components you have put together.  I would like to see you get more visibility with these projects.  Websockets bridge to zeroMQ - genius!  I saw a thread on Google Groups regarding performance and the potential for scaling and performant smartphone apps (via websockets).  I plan to give this a shot.  I think it is ideal.  Let me know if you want my help getting the word out - I will be happy to lend a hand.
-ross
