### ISSUE TITLE
NameError in di.py

### ISSUE THREAD

**Issue by lud4ik** [tailhook/zorro#11]
<pre><code>
class World:
    pass

@has_dependencies
class Hello:
    world = dependency(World, 'universe')

inj = DependencyInjector()
inj['universe'] = World()

hello = inj.inject_restricted(Hello())
assert hello.world is inj['universe']
</code></pre>

result in

<pre><code>
Original exception was:
Traceback (most recent call last):
  File "di.py", line 208, in <module>
    hello = inj.inject_restricted(Hello())
  File "di.py", line 140, in inject_restricted
    for name in names:
NameError: global name 'names' is not defined
</code></pre>

line 134 
"and propagates only this instance's dependencies" mean:

<pre><code>
line 132 

    def inject_restricted(self, inst):
        """Injects dependencies, and propagates only this instance's
        dependencies
        """
        di = self.__class__()
        mypro = self._provides
        pro = di._provides
        inst.__zorro_di__ = di
        deps = getattr(inst, '__zorro_depends__', None)
        if deps:
            for attr, dep in deps.items():
                pro[dep.name] = mypro[dep.name]
                val = pro[dep.name]
                if not isinstance(val, dep.type):
                    raise RuntimeError("Wrong provider for {!r}".format(val))
                setattr(inst, attr, val)
        meth = getattr(inst, '__zorro_di_done__', None)
        if meth is not None:
            meth()
        return inst
</code></pre>

?

**Comment by tailhook** [comment]
Nice. It means "inject_restricted" have never been used, it was kinda over-engineering. Do you have a use case, or can I just remove the method?

**Comment by lud4ik** [comment]
It's your code. Do what you want.

**Comment by tailhook** [comment]
Done.
